### ISSUE TITLE
Question about the rescale ratio for diffuse color

### ISSUE THREAD

**Issue by mush881212** [Haian-Jin/TensoIR#16]
Hi,

I am a student with a keen interest in the topic at hand. While exploring your repository, I came across the "relight_importance.py" script and noticed the presence of a "compute_rescale_ratio" function. 
It appears that this computed ratio is intended for the purpose of rescaling the diffuse color. 
I am curious to understand the specific rationale behind this rescaling process. In my view, it might be possible to achieve the desired relighting results using the original, unaltered diffuse color.

Thanks for your amazing work and look forward to your reply.

**Comment by Haian-Jin** [comment]
Hi, We follow what has been done in NeRFactor, i.e. when visualizing and measuring the reconstructed albedo, we will compute and use a global factor to rescale the albedo reconstruction results.

Please check the Sec. 4.2 of NeRFactor's paper for more details.
