### ISSUE TITLE
could you provide Armadillo.blend

### ISSUE THREAD

**Issue by yijiaguo02** [Haian-Jin/TensoIR#20]
could you provide Armadillo.blend

**Comment by Haian-Jin** [comment]
Hi,

I just added this .blend file to the rendering scripts.
<img width="906" alt="image" src="https://github.com/Haian-Jin/TensoIR/assets/79512936/8763167f-e136-4bd6-8b73-79329b63747b">

Please let me know if you have more questions.

Best,
Haian

**Comment by yijiaguo02** [comment]
Thanks a lot. I don't have any questions now.
Best wishes
