### ISSUE TITLE
Problems Generating My new dataset

### ISSUE THREAD

**Issue by ealicesora** [Haian-Jin/TensoIR#4]
Hello! Thanks for your great work. We are really impressed by reconstruction quality has achieved.
We had followed 'Generating your own synthetic dataset' for the code generating out new scenes with a single small cube, and try to reconstruct it by this project.
However we found it doesn't work and the reuslt is pretty blurry. We had made the backgroud transparency like the armadillo in TensoIR-Synthetic.(using  train_tensoIR.py )
After diving into the code about photos genreation and this project, we found the code to genreate new pictures with blender reamin some inconsistency with this project, especially generating camera params in the json file(camera_angle_x, rotation,  rgba_xxsscene_000.png etc) I had fixed some, but it still remain some inconsistency.
Would you give me some advice about how to import my own scenes description into this project?(orientation of Z-axis, or is 'rotation' used in json? ) Or maybe could you share me you latest dataset generation code for blender?(the code in 'Generating your own synthetic dataset' dosen't seems to be latest)
Thanks!
(I am sorry maybe I am not a good English Speaker, if you feeled confused what I am talking about, maybe I can use Chinese

**Comment by Haian-Jin** [comment]
Hi, thanks for your interest in this work!
Sorry, I didn't get your point. Can you give more details and descriptions of your problem? (maybe show some result pictures) I shared the code for generating a new dataset with one of my friends before I released it and he didn't meet any problems and told me it worked well, so the code should be OK. 
Though I prefer communicating in English here, If you think it will be easier for you to describe your problem in Chinese, you can still use it.

**Comment by ealicesora** [comment]
Thanks for your cooperation, I found the reason led to the abnormal results. It's due to my customize to the camera positions for the scenes,(I tried to push the camera close to the object) and there is a near_far parameter I didn't noticed in TensorBase which makes the near plane intersect with object.
