### ISSUE TITLE
How to Extract maps which can be used in UE?

### ISSUE THREAD

**Issue by semchan** [Haian-Jin/TensoIR#8]
Great job. I have seen that it is possible to export mesh, but I would like to know how to export texture maps so that they can be used in UE rendering engines effectively. Thanks a lot.

**Comment by Haian-Jin** [comment]
Thank you for your interest in this work!

To answer your question, I have not yet implemented this feature now.

It would require querying the BRDF and normals for each mesh vertex in 3D space, which involves first obtaining the intrinsic feature of the mesh vertex and then querying the corresponding MLPs. After obtaining the BRDF and normals, they would need to be mapped into a material textures map and normal map using some graphics algorithm.

If you tried it by yourself, please feel free to tell me if you have further questions.

**Comment by YiChenCityU** [comment]
It would be helpful to implement texture export function.
